#!/usr/bin/env bash
# Displays information about subdomains
if [ $# -eq 1 ]; then
	queries="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
	queries="$2.$1"
fi
dig $queries | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
